version: '3'

services:
  backend:
    build: ./backend
    env_file:
      - ./.env

    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  mysql_data: