version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  mysql_data: